spring:
  datasource:
    url: jdbc:h2:./database/vending-machine;AUTO_SERVER=TRUE
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
server:
  servlet:
    context-path: /vending-machine
  port: 9090
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger.html
security:
  jwt:
    privateKey: classpath:private.key
    publicKey: classpath:public.key
    expiresInSeconds: 360
    issuer: vending-machine